[package]
name = "flightthepower"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
bevy = "0.15.1"
bevy_asset_loader = { version = "0.22.0", features = ["2d"] }
rand = "0.9.0"
serde = "1.0.217"
